--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

-- Started on 2021-04-23 10:59:45

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 16411)
-- Name: test; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA test;


ALTER SCHEMA test OWNER TO postgres;

--
-- TOC entry 218 (class 1255 OID 24601)
-- Name: cable_check(); Type: FUNCTION; Schema: test; Owner: postgres
--

CREATE FUNCTION test.cable_check() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE id_RP_out integer;
		id_TP_out integer;
		id_RP_in integer;
		id_TP_in integer;
BEGIN
	id_RP_out := (SELECT "id_RP_out" FROM test."Cable_line" ORDER BY "id_cable" DESC LIMIT 1);
	id_TP_out := (SELECT "id_TP_out" FROM test."Cable_line" ORDER BY "id_cable" DESC LIMIT 1);
	id_RP_in := (SELECT "id_RP_in" FROM test."Cable_line" ORDER BY "id_cable" DESC LIMIT 1);
	id_TP_in := (SELECT "id_TP_in" FROM test."Cable_line" ORDER BY "id_cable" DESC LIMIT 1);
	IF ((id_RP_out IS NULL AND id_TP_out IS NULL) OR (id_RP_out IS NOT NULL AND id_TP_out IS NOT NULL)) THEN
		RAISE EXCEPTION 'Должен быть один источник';
	ELSEIF ((id_RP_in IS NULL AND id_TP_in IS NULL) OR (id_RP_in IS NOT NULL AND id_TP_in IS NOT NULL)) THEN
		RAISE EXCEPTION 'Должен быть один получатель';
	ELSEIF (id_TP_out IS NOT NULL AND id_RP_in IS NOT NULL) THEN
		RAISE EXCEPTION 'ТП не может быть источником для РП';
	ELSEIF (id_TP_out =  id_TP_in OR id_RP_out =  id_RP_in) THEN
		RAISE EXCEPTION 'Кабель не может приходить в тот-же объект';
	END IF;
	RETURN NULL;
END;
$$;


ALTER FUNCTION test.cable_check() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 206 (class 1259 OID 16948)
-- Name: Cable_line; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test."Cable_line" (
    id_cable integer NOT NULL,
    length integer NOT NULL,
    section integer NOT NULL,
    transmitted_power integer NOT NULL,
    bandwidth integer NOT NULL,
    "id_RP_out" integer,
    "id_TP_out" integer,
    "id_RP_in" integer,
    "id_TP_in" integer
);


ALTER TABLE test."Cable_line" OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 16428)
-- Name: D_substation; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test."D_substation" (
    "id_RP" integer NOT NULL,
    coordinates point NOT NULL
);


ALTER TABLE test."D_substation" OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 16426)
-- Name: D_substation_id_RP_seq; Type: SEQUENCE; Schema: test; Owner: postgres
--

ALTER TABLE test."D_substation" ALTER COLUMN "id_RP" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME test."D_substation_id_RP_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 16449)
-- Name: Diesel_generator; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test."Diesel_generator" (
    "id_DGU" integer NOT NULL,
    power integer NOT NULL,
    coordinates point NOT NULL
);


ALTER TABLE test."Diesel_generator" OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 16447)
-- Name: Diesel_generator_id_DGU_seq; Type: SEQUENCE; Schema: test; Owner: postgres
--

ALTER TABLE test."Diesel_generator" ALTER COLUMN "id_DGU" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME test."Diesel_generator_id_DGU_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 201 (class 1259 OID 16421)
-- Name: T_substation; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test."T_substation" (
    "id_TP" integer NOT NULL,
    total_power_of_consumers integer NOT NULL,
    transformer_power integer NOT NULL,
    electrical_reliability integer NOT NULL,
    coordinates point NOT NULL
);


ALTER TABLE test."T_substation" OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 16419)
-- Name: T_substation_id_TP_seq; Type: SEQUENCE; Schema: test; Owner: postgres
--

ALTER TABLE test."T_substation" ALTER COLUMN "id_TP" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME test."T_substation_id_TP_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3016 (class 0 OID 16948)
-- Dependencies: 206
-- Data for Name: Cable_line; Type: TABLE DATA; Schema: test; Owner: postgres
--

INSERT INTO test."Cable_line" (id_cable, length, section, transmitted_power, bandwidth, "id_RP_out", "id_TP_out", "id_RP_in", "id_TP_in") VALUES (1, 1, 1, 2, 2, 1, NULL, NULL, 1);
INSERT INTO test."Cable_line" (id_cable, length, section, transmitted_power, bandwidth, "id_RP_out", "id_TP_out", "id_RP_in", "id_TP_in") VALUES (2, 1, 1, 2, 2, 1, NULL, NULL, 1);


--
-- TOC entry 3013 (class 0 OID 16428)
-- Dependencies: 203
-- Data for Name: D_substation; Type: TABLE DATA; Schema: test; Owner: postgres
--

INSERT INTO test."D_substation" ("id_RP", coordinates) VALUES (1, '(2,1)');


--
-- TOC entry 3015 (class 0 OID 16449)
-- Dependencies: 205
-- Data for Name: Diesel_generator; Type: TABLE DATA; Schema: test; Owner: postgres
--

INSERT INTO test."Diesel_generator" ("id_DGU", power, coordinates) VALUES (1, 1, '(1,1)');


--
-- TOC entry 3011 (class 0 OID 16421)
-- Dependencies: 201
-- Data for Name: T_substation; Type: TABLE DATA; Schema: test; Owner: postgres
--

INSERT INTO test."T_substation" ("id_TP", total_power_of_consumers, transformer_power, electrical_reliability, coordinates) VALUES (1, 1, 1, 1, '(1,1)');


--
-- TOC entry 3022 (class 0 OID 0)
-- Dependencies: 202
-- Name: D_substation_id_RP_seq; Type: SEQUENCE SET; Schema: test; Owner: postgres
--

SELECT pg_catalog.setval('test."D_substation_id_RP_seq"', 1, false);


--
-- TOC entry 3023 (class 0 OID 0)
-- Dependencies: 204
-- Name: Diesel_generator_id_DGU_seq; Type: SEQUENCE SET; Schema: test; Owner: postgres
--

SELECT pg_catalog.setval('test."Diesel_generator_id_DGU_seq"', 1, false);


--
-- TOC entry 3024 (class 0 OID 0)
-- Dependencies: 200
-- Name: T_substation_id_TP_seq; Type: SEQUENCE SET; Schema: test; Owner: postgres
--

SELECT pg_catalog.setval('test."T_substation_id_TP_seq"', 1, false);


--
-- TOC entry 2874 (class 2606 OID 16952)
-- Name: Cable_line Cable_line_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test."Cable_line"
    ADD CONSTRAINT "Cable_line_pkey" PRIMARY KEY (id_cable);


--
-- TOC entry 2870 (class 2606 OID 16432)
-- Name: D_substation D_substation_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test."D_substation"
    ADD CONSTRAINT "D_substation_pkey" PRIMARY KEY ("id_RP");


--
-- TOC entry 2872 (class 2606 OID 16453)
-- Name: Diesel_generator Diesel_generator_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test."Diesel_generator"
    ADD CONSTRAINT "Diesel_generator_pkey" PRIMARY KEY ("id_DGU");


--
-- TOC entry 2868 (class 2606 OID 16425)
-- Name: T_substation T_substation_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test."T_substation"
    ADD CONSTRAINT "T_substation_pkey" PRIMARY KEY ("id_TP");


--
-- TOC entry 2879 (class 2620 OID 24602)
-- Name: Cable_line cable_ln; Type: TRIGGER; Schema: test; Owner: postgres
--

CREATE TRIGGER cable_ln AFTER INSERT OR UPDATE ON test."Cable_line" FOR EACH ROW EXECUTE FUNCTION test.cable_check();


--
-- TOC entry 2875 (class 2606 OID 16953)
-- Name: Cable_line Cable_line_id_RP_in_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test."Cable_line"
    ADD CONSTRAINT "Cable_line_id_RP_in_fkey" FOREIGN KEY ("id_RP_in") REFERENCES test."D_substation"("id_RP") ON DELETE CASCADE;


--
-- TOC entry 2878 (class 2606 OID 16968)
-- Name: Cable_line Cable_line_id_RP_out_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test."Cable_line"
    ADD CONSTRAINT "Cable_line_id_RP_out_fkey" FOREIGN KEY ("id_RP_out") REFERENCES test."D_substation"("id_RP") ON DELETE CASCADE;


--
-- TOC entry 2877 (class 2606 OID 16963)
-- Name: Cable_line Cable_line_id_TP_in_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test."Cable_line"
    ADD CONSTRAINT "Cable_line_id_TP_in_fkey" FOREIGN KEY ("id_TP_in") REFERENCES test."T_substation"("id_TP") ON DELETE CASCADE;


--
-- TOC entry 2876 (class 2606 OID 16958)
-- Name: Cable_line Cable_line_id_TP_out_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test."Cable_line"
    ADD CONSTRAINT "Cable_line_id_TP_out_fkey" FOREIGN KEY ("id_TP_out") REFERENCES test."T_substation"("id_TP") ON DELETE CASCADE;


-- Completed on 2021-04-23 10:59:45

--
-- PostgreSQL database dump complete
--

